name: Process Kindle Notes # This workflow will run email processing at X:X0 (e.g., 1:00, 1:10, 1:20, etc.) and run text processing at X:X1 (e.g., 1:01, 1:11, 1:21, etc.)

on:
  workflow_dispatch:  # Allows manual trigger if needed
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes, will coordinate with job-level timing

jobs:
  process-emails:
    runs-on: ubuntu-latest
    steps:
      - name: Process Kindle Emails
        run: |
          # Wait until we're at the start of a 10-minute interval
          sleep $(( 60 - $(date +%s) % 60 ))
          
          echo "Processing Kindle emails..."
          response=$(curl -s -w "\n%{http_code}" "https://kindle-notebook-download.vercel.app/api/index")
          status_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | head -n-1)
          
          if [ "$status_code" = "200" ]; then
            echo "Email processing complete: $body"
          else
            echo "Error processing emails: $body"
            exit 1
          fi

  process-text:
    runs-on: ubuntu-latest
    steps:
      - name: Process Text Files
        run: |
          # Wait until we're 1 minute past a 10-minute interval
          sleep $(( 60 - $(date +%s) % 60 + 60 ))
          
          echo "Processing text files..."
          while true; do
            response=$(curl -s -w "\n%{http_code}" "https://kindle-notebook-download.vercel.app/api/distill_text")
            status_code=$(echo "$response" | tail -n1)
            body=$(echo "$response" | head -n-1)
            
            if [ "$status_code" = "200" ]; then
              echo "All files processed: $body"
              break
            elif [ "$status_code" = "307" ]; then
              echo "More files to process: $body"
              sleep 5
            else
              echo "Error processing files: $body"
              exit 1
            fi
          done